services:
  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    ports:
      # Local Spring Boot services connect to Kafka through this port.
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1

      # Kafka runs without ZooKeeper in KRaft mode.
      KAFKA_PROCESS_ROLES: broker,controller

      # Internal controller configuration for the single Kafka node.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Kafka listeners:
      # kafka:9092 is used by other Docker containers
      # kafka:9093 is used internally by Kafka controller
      # 0.0.0.0:9094 is exposed to your host machine
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9094

      # Advertised addresses:
      # kafka:9092       is used by Docker containers
      # localhost:9094   is used by local Spring Boot apps
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094

      # Listener protocol mapping.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      # Kafka controller listener.
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Broker-to-broker communication listener.
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Required for a single-node development Kafka setup.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # With this, Kafka can create topics automatically when the app first uses them.
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - shopping-platform-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      # Kafka UI can be opened in the browser at http://localhost:8090
      - "8090:8080"
    environment:
      # Name shown inside Kafka UI.
      KAFKA_CLUSTERS_0_NAME: local-kafka

      # Kafka UI runs inside Docker, so it connects to Kafka using the Docker-internal address.
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - shopping-platform-network

networks:
  shopping-platform-network:
    external: true