# Use this file as a template to create application-local.properties file to store your local db credentials
spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://order_db:5432/order_service}
spring.datasource.username=${ORDER_DB_USER:your_local_db_username_here}
spring.datasource.password=${ORDER_DB_PASS:your_local_db_password_here}