spring.application.name=order_service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Port number can be changed in server.port property
server.port=8081
spring.main.banner-mode=off

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${ORDER_DB_URL:NOT_CONFIGURED}

spring.datasource.username=${ORDER_DB_USER:NOT_CONFIGURED}
spring.datasource.password=${ORDER_DB_PASS:NOT_CONFIGURED}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Kafka properties
spring.kafka.bootstrap-servers=localhost:9094

# Kafka topics
app.kafka.topics.order-created=order-created
app.kafka.topics.inventory-item-reservation-result=inventory-item-reservation-result

# Kafka producer properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Kafka producer event type mappings
spring.kafka.producer.properties.spring.json.type.mapping=OrderCreatedEvent:com.suleyman6001.order_service.kafka.event.OrderCreatedEvent

# Kafka consumer properties
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Kafka consumer event type mappings
spring.kafka.consumer.properties.spring.json.type.mapping=InventoryItemReservationResultEvent:com.suleyman6001.order_service.kafka.event.InventoryItemReservationResultEvent
